import React from 'react';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Image from 'react-bootstrap/Image'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub } from '@fortawesome/free-brands-svg-icons'

import planTracker from "../assets/images/PlanTracker.PNG"
import gitIdeas from "../assets/images/GIT-IDEAS.png"
import weatherDash from "../assets/images/WDAustin.png"
import employeeTrack from "../assets/images/EmployeeTracker.png"
import teamProfGen from "../assets/images/TeamProfileGen.png"
import codingQuiz from "../assets/images/CodingQuiz.png"

export default function Projects() {
  return (
    <div>
      <h1>Projects</h1>
      <Container>
      <Row>
        <Col>
          <div className='project-container'>
            <Image fluid className='project-img' src={planTracker} alt="Plan Tracker webpage." />
            <div className='middle'>
              <div className='text'>
              <h3>
                <a href="https://plan-tracker-app.herokuapp.com/" target="_blank">Plan Tracker</a>
                <span>
                  <a href="https://github.com/kpeazzoni/plan-tracker-app" target="_blank"><FontAwesomeIcon className='project-brand-icons' icon={faGithub} size="1x" />
                  </a>
                </span>
              </h3>
              <p>MERN Stack</p>
              </div>
            </div>
          </div>
        </Col>
        <Col>
          <div className='project-container'>
            <Image fluid className='project-img' src={gitIdeas} alt="GIT-IDEAS webpage." />
            <div className='middle'>
              <div className='text'>
              <h3>
                <a href="https://git-ideas.herokuapp.com/" target="_blank">Git-Ideas</a>
                <span>
                  <a href="https://github.com/SeanAllen19/GIT-IDEAS" target="_blank"><FontAwesomeIcon className='project-brand-icons' icon={faGithub} size="1x" />
                  </a>
                </span>
              </h3>
              <p>MERN Stack</p>
              </div>
            </div>
          </div>
        </Col>
      </Row>

      <Row>
        <Col>
        <a href="https://re-gi.github.io/UTA_Weather-Dashboard" target="_blank">
          <div className='project-container'>
            <Image fluid className='project-img' src={weatherDash} alt="Weather Dashboard webpage." />
            <div className='middle'>
              <div className='text'>
              <h3>
                <a href="https://re-gi.github.io/UTA_Weather-Dashboard" target="_blank">Weather Dashboard</a>
                <span>
                  <a href="https://github.com/Re-Gi/UTA_Weather-Dashboard" target="_blank"><FontAwesomeIcon className='project-brand-icons' icon={faGithub} size="1x" />
                  </a>
                </span>
              </h3>
              <p>MERN Stack</p>
              </div>
            </div>
          </div>
        </a>
        </Col>
        <Col>
          <div className='project-container'>
            <Image fluid className='project-img' src={employeeTrack} alt="Employee Tracker being used in a Visual Studio Code terminal." />
            <div className='middle'>
              <div className='text'>
              <h3>
                Employee Tracker
                <span>
                  <a href="https://github.com/Re-Gi/UTA_Employee-Tracker" target="_blank"><FontAwesomeIcon className='project-brand-icons' icon={faGithub} size="1x" />
                  </a>
                </span>
              </h3>
              <p>MERN Stack</p>
              </div>
            </div>
          </div>
        </Col>
      </Row>

      <Row>
        <Col>
          <div className='project-container'>
            <Image fluid className='project-img' src={teamProfGen} alt="HTML page generated by the Team Profile Generator." />
            <div className='middle'>
              <div className='text'>
              <h3>
                Team Profile Generator
                <span>
                  <a href="https://github.com/Re-Gi/UTA_Team-Profile-Generator" target="_blank"><FontAwesomeIcon className='project-brand-icons' icon={faGithub} size="1x" />
                  </a>
                </span>
              </h3>
              <p>MERN Stack</p>
              </div>
            </div>
          </div>
        </Col>
        <Col>
        
          <div className='project-container'>
            <Image fluid className='project-img' src={codingQuiz} alt="The Coding Quiz webpage" />
            <div className='middle'>
              <div className='text'>
              <h3>
                <a href="https://re-gi.github.io/UTA_Coding-Quiz/" target="_blank">The Coding Quiz</a>
                <span>
                  <a href='https://github.com/Re-Gi/UTA_Coding-Quiz' target="_blank"><FontAwesomeIcon className='project-brand-icons' icon={faGithub} size="1x" />
                  </a>
                </span>
              </h3>
              <p>MERN Stack</p>
              </div>
            </div>
          </div>
        </Col>
      </Row>
    </Container>
      {/* <div className='outer-projects-container'>
                <div className="box">
                    <a href="https://plan-tracker-app.herokuapp.com/" target="_blank">
                        <h4>Plan Tracker<p><i>FULL-STACK MERN</i> |
                             Express.js, React.js, MongoDB, Node.js bootstrap, mongoose, apollo, graphql, jsonwebtoken, dev-express</p>
                        </h4>
                        <img src={planTracker}
                            alt="Plan Tracker webpage." />
                    </a>
                </div>

                <div className="box">
                    <a href="https://git-ideas.herokuapp.com/" target="_blank">
                        <h4>GIT-IDEAS<p><i>FULL-STACK</i> |
                            Express.js, Handlebars, GitHub REST API axios, bcrypt.js, dotenv, mysql2, sequelize, express-session</p>
                       </h4>
                       <img src={gitIdeas}
                           alt="GIT-IDEAS webpage." />
                   </a>
                </div>

                <div className="box">
                    <a href="https://re-gi.github.io/UTA_Weather-Dashboard" target="_blank">
                        <h4>Weather Dashboard<p>HTML, CSS, JavaScript OpenWeatherMap API, Bootstrap, Day.js</p>
                        </h4>
                        <img src={weatherDash}
                            alt="Weather Dashboard webpage." />
                    </a>
                </div>

                <div className="box">
                    <a href="https://github.com/Re-Gi/UTA_Employee-Tracker" target="_blank">
                        <h4>Employee Tracker<p>JavaScript, SQL, MySQL Inquirer, mysql2, console.table, dotenv</p>
                        </h4>
                        <img src={employeeTrack}
                            alt="Employee Tracker being used in a Visual Studio Code terminal." />
                    </a>
                </div>

                <div className="box">
                    <a href="https://github.com/Re-Gi/UTA_Team-Profile-Generator" target="_blank">
                        <h4>Team Profile Generator<p>HTML, CSS, JavaScript Inquirer, Jest</p>
                        </h4>
                        <img src={teamProfGen}
                            alt="HTML page generated by the Team Profile Generator." />
                    </a>
                </div>

                <div className="box">
                    <a href="https://re-gi.github.io/UTA_Coding-Quiz/" target="_blank">
                        <h4>Coding Quiz<p>HTML, CSS, JavaScript</p>
                        </h4>
                        <img src={codingQuiz} alt="The Coding Quiz webpage" />
                    </a>
                </div>
            </div> */}
    </div>
  );
}